def load_disney():
    """ List retrieved from https://en.wikipedia.org/wiki/List_of_Walt_Disney_Animation_Studios_films """
    disney = [
             'Snow White and the Seven Dwarfs',
             'Pinocchio',
             'Fantasia',
             'Dumbo',
             'Bambi',
             'Saludos Amigos',
             'The Three Caballeros',
             'Make Mine Music',
             'Fun and Fancy Free',
             'Melody Time',
             'The Adventures of Ichabod and Mr. Toad',
             'Cinderella',
             'Alice in Wonderland',
             'Peter Pan',
             'Lady and the Tramp',
             'Sleeping Beauty',
             'One Hundred and One Dalmatians',
             'The Sword in the Stone',
             'The Jungle Book',
             'The Aristocats',
             'Robin Hood',
             'The Many Adventures of Winnie the Pooh',
             'The Rescuers',
             'The Fox and the Hound',
             'The Black Cauldron',
             'The Great Mouse Detective',
             'Oliver & Company',
             'The Little Mermaid',
             'The Rescuers Down Under',
             'Beauty and the Beast',
             'Aladdin',
             'The Lion King',
             'Pocahontas',
             'The Hunchback of Notre Dame',
             'Hercules',
             'Mulan',
             'Tarzan',
             'Fantasia 2000',
             'Dinosaur',
             "The Emperor's New Groove",
             'Atlantis: The Lost Empire',
             'Lilo & Stitch',
             'Treasure Planet',
             'Brother Bear',
             'Home on the Range',
             'Chicken Little',
             'Meet the Robinsons',
             'Bolt',
             'The Princess and the Frog',
             'Tangled',
             'Winnie the Pooh',
             'Wreck-It Ralph',
             'Frozen',
             'Big Hero 6',
             'Zootopia',
             'Moana',
             'Ralph Breaks the Internet',
             'Frozen II']
    return disney


def load_pixar():
    """ List retrieved from: https://en.m.wikipedia.org/wiki/List_of_Pixar_films """
    pixar = ["Toy Story",
             "A Bug's Life",
             "Toy Story 2",
             "Monsters, Inc.",
             "Finding Nemo",
             "The Incredibles",
             "Cars",
             "Ratatouille",
             "WALL·E",
             "Up",
             "Toy Story 3",
             "Cars 2",
             "Brave",
             "Monsters University",
             "Inside Out",
             "The Good Dinosaur",
             "Finding Dory",
             "Cars 3",
             "Coco",
             "Incredibles 2",
             "Toy Story 4",
             "Onward"]
    
    return pixar
